name: prek
description: Run prek

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "1"
        filter: "blob:none"
    - uses: astral-sh/setup-uv@v6
    - name: Install prek
      shell: bash -e {0}
      run: |
        uv tool install prek
    - uses: actions/cache/restore@v4
      with:
        path: ~/.cache/prek
        key: prek|${{ hashFiles('.pre-commit-config.yaml') }}
      id: cache
    - name: Run prek
      shell: bash {0}
      run: |
        prek run --all-files --show-diff-on-failure --color=always | tee /tmp/prek.log >&1
        exit_code=${PIPESTATUS[0]}

        echo '```console' > $GITHUB_STEP_SUMMARY
        sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' /tmp/prek.log >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

        exit $exit_code
    - if: always() && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/prek
        key: prek|${{ hashFiles('.pre-commit-config.yaml') }}
