name: pre-commit
description: Run pre-commit
inputs:
  python-version:
    description: Python version to use
    default: "3.12"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "1"
        filter: "blob:none"
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install pre-commit
      shell: bash -e {0}
      run: |
        uv tool install pre-commit --with pre-commit-uv
    - uses: actions/cache/restore@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ inputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
      id: cache
    - name: Run pre-commit
      shell: bash {0}
      run: |
        # Pre-commit
        pre-commit run --all-files --show-diff-on-failure --color=always | tee /tmp/pre-commit.log >&1
        exit_code=${PIPESTATUS[0]}

        echo '```console' > $GITHUB_STEP_SUMMARY
        sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?[mGK]//g' /tmp/pre-commit.log >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

        exit $exit_code
    - if: always() && steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ inputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
